name: build-beta-ios
on:
  push:
    branches:
      - 'beta'
jobs:
  checkout:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
  build:
    needs: [checkout]
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.3.0
        with:
          lane: 'beta'
          subdirectory: 'ios'