name: build-android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        run: |
          npm install
  build-android:
    needs: install-deps
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
